export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED ='LOGIN_FAILED'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAILED = 'RESET_PASSWORD_CONFIRM_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAILED = 'USER_LOADED_FAILED'

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAILED = 'AUTHENTICATED_FAILED'

export const BLOG_POST_SUCCESS = 'BLOG_POST_SUCCESS'
export const BLOG_POST_FAILED = 'BLOG_POST_FAILED'

export const BLOG_GET_SUCCESS = 'BLOG_GET_SUCCESS'
export const BLOG_GET_FAILED = 'BLOG_GET_FAILED'

export const GET_USER_ARICLES_SUCCESS = 'GET_USER_ARICLE_SUCCESS'
export const GET_USER_ARICLES_FAILED = 'GET_USER_ARICLE_FAILED'

export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED'

